from __future__ import annotations

from typing import Any

from siftguard.agent.case_manifest_adapter import AdaptedCaseManifest
from siftguard.agent.casebook import Casebook
from siftguard.agent.models import AgentRun


def _decision(
    *,
    decision_id: str,
    phase: str,
    question: str,
    available_inputs: dict[str, Any],
    selected_action: str,
    rationale: str,
    expected_outputs: list[str],
    outcome: str,
    next_action: str,
) -> dict[str, Any]:
    return {
        "decision_id": decision_id,
        "phase": phase,
        "question": question,
        "available_inputs": available_inputs,
        "selected_action": selected_action,
        "rationale": rationale,
        "expected_outputs": expected_outputs,
        "outcome": outcome,
        "next_action": next_action,
    }


def build_decision_trace(
    *,
    adapted: AdaptedCaseManifest,
    run: AgentRun,
    casebook: Casebook | None,
    case_questions: dict[str, Any] | None,
    warnings: list[str],
    created_at: str,
    event_selection_profile: str,
    max_normalized_events: int | None,
) -> dict[str, Any]:
    question_count = 0
    status_counts: dict[str, Any] = {}
    if case_questions is not None:
        rows = case_questions.get("questions", [])
        question_count = len(rows) if isinstance(rows, list) else 0
        counts = case_questions.get("status_counts", {})
        status_counts = dict(counts) if isinstance(counts, dict) else {}

    decisions = [
        _decision(
            decision_id="artifact_manifest_intake",
            phase="intake",
            question="Can the prepared case manifest be used as bounded agent input?",
            available_inputs={
                "artifact_manifest": adapted.case_prep_path.name,
                "prepared_artifact_count": len(adapted.prepared_artifacts),
                "source_count": len(adapted.sources),
            },
            selected_action=(
                "Use parser-eligible prepared artifacts and preserve source provenance."
            ),
            rationale=(
                "The manifest was generated by SIFTGuard case preparation and carries "
                "source IDs."
            ),
            expected_outputs=["adapted_manifest.json"],
            outcome="completed",
            next_action="Verify source provenance before casebook mapping.",
        ),
        _decision(
            decision_id="provenance_verification",
            phase="intake",
            question="Does each selected artifact preserve source provenance?",
            available_inputs={
                "source_count": len(adapted.sources),
                "prepared_artifact_count": len(adapted.prepared_artifacts),
                "parser_artifact_count": len(adapted.evidence_manifest.artifacts),
            },
            selected_action="Require source IDs before mapping prepared artifacts to evidence.",
            rationale=(
                "Case-question outputs must be traceable back to prepared artifacts "
                "and source records."
            ),
            expected_outputs=["adapted_manifest.json", "case_questions.json"],
            outcome="completed",
            next_action="Load casebook and choose supported forensic scope.",
        ),
        _decision(
            decision_id="casebook_intake" if casebook is not None else "casebook_absent_fallback",
            phase="intake",
            question="Is a JSON casebook available for case-question mapping?",
            available_inputs={
                "casebook_present": casebook is not None,
                "casebook_id": casebook.case_id if casebook is not None else None,
            },
            selected_action=(
                "Use JSON casebook questions."
                if casebook is not None
                else "Continue with manifest-only output and record warning."
            ),
            rationale=(
                "Casebook provides explicit case questions and analysis windows."
                if casebook is not None
                else "Casebook is optional for run-case compatibility."
            ),
            expected_outputs=["case_questions.json", "gap_analysis.json"],
            outcome="completed" if casebook is not None else "fallback",
            next_action="Select supported artifacts and preserve out-of-scope sources.",
        ),
        _decision(
            decision_id="supported_source_artifact_selection",
            phase="scope",
            question="Which sources and prepared artifacts are inside final scope?",
            available_inputs={
                "parser_artifact_count": len(adapted.evidence_manifest.artifacts),
                "memory_source_count": len(adapted.memory_sources),
                "case_background_count": len(adapted.case_background_sources),
            },
            selected_action="Run disk-derived parser-eligible artifacts only.",
            rationale=(
                "Final scope supports $MFT, Registry Run/RunOnce, and Amcache; "
                "memory is provenance only."
            ),
            expected_outputs=["normalized_events.json", "coverage_summary.json"],
            outcome="completed",
            next_action="Plan deterministic parser workflow.",
        ),
        _decision(
            decision_id="memory_source_handling",
            phase="scope",
            question="How should staged memory sources be handled?",
            available_inputs={
                "memory_sources": [
                    {
                        "source_id": source.get("source_id"),
                        "analysis_scope": source.get("analysis_scope"),
                    }
                    for source in adapted.memory_sources
                ]
            },
            selected_action="Mark memory not_assessed and exclude memory forensics.",
            rationale="Memory forensics is outside final submission scope.",
            expected_outputs=["gap_analysis.json", "case_questions.json"],
            outcome="completed",
            next_action="Execute supported parser plan.",
        ),
        _decision(
            decision_id="parser_plan_selection",
            phase="parse",
            question="Which parser plan should run against prepared artifacts?",
            available_inputs={
                "event_selection_profile": event_selection_profile,
                "max_normalized_events": max_normalized_events,
            },
            selected_action="Use deterministic parser workflow with bounded event selection.",
            rationale=(
                "Registry and Amcache observations are preserved before bounded MFT "
                "selection."
            ),
            expected_outputs=["normalized_events.json", "coverage_summary.json"],
            outcome=run.status.value,
            next_action="Correlate normalized events.",
        ),
        _decision(
            decision_id="event_selection_strategy",
            phase="parse",
            question="How should selected events be bounded for triage?",
            available_inputs={
                "event_selection_profile": event_selection_profile,
                "analysis_window_count": len(casebook.analysis_windows) if casebook else 0,
            },
            selected_action=(
                "Prefer high-signal artifacts and case-window MFT events within the cap."
            ),
            rationale=(
                "Bounded triage should keep case-window evidence without discarding "
                "Registry or Amcache."
            ),
            expected_outputs=["coverage_summary.json"],
            outcome="completed",
            next_action="Build timelines and validate findings.",
        ),
        _decision(
            decision_id="correlation_strategy",
            phase="correlate",
            question="How should normalized events be grouped?",
            available_inputs={"workflow_status": run.status.value},
            selected_action="Reuse existing deterministic subject timeline correlation.",
            rationale=(
                "The case-question layer should add interpretation without duplicating "
                "correlation logic."
            ),
            expected_outputs=["subject_timelines.json", "findings.json"],
            outcome="completed",
            next_action="Map findings and events to case questions.",
        ),
        _decision(
            decision_id="validation_strategy",
            phase="validate",
            question="How should findings be validated before report use?",
            available_inputs={"workflow_status": run.status.value},
            selected_action="Reuse existing verifier and require evidence-linked findings.",
            rationale=(
                "Confirmed or inferred records must stay evidence-backed; unsupported "
                "claims are not trusted."
            ),
            expected_outputs=["findings.json", "agent_run.json"],
            outcome="completed",
            next_action="Apply bounded correction behavior if validation fails.",
        ),
        _decision(
            decision_id="correction_strategy",
            phase="correct",
            question="How should unsupported or incomplete claims be handled?",
            available_inputs={
                "warning_count": len(warnings),
                "workflow_status": run.status.value,
            },
            selected_action="Keep unsupported questions not_assessed or needs_review.",
            rationale=(
                "The workflow must not convert missing theft, transfer, exfiltration, "
                "or memory evidence into positive claims."
            ),
            expected_outputs=["findings.json", "gap_analysis.json"],
            outcome="completed",
            next_action="Map findings and events to case questions.",
        ),
        _decision(
            decision_id="case_question_mapping",
            phase="case_questions",
            question="How do selected events answer the case questions?",
            available_inputs={
                "question_count": question_count,
                "status_counts": status_counts,
            },
            selected_action="Map evidence classes and findings to each casebook question.",
            rationale=(
                "Explicit question mapping prevents unsupported theft/exfiltration "
                "conclusions."
            ),
            expected_outputs=["case_questions.json"],
            outcome="completed" if casebook is not None else "not_available",
            next_action="Assign strict status thresholds.",
        ),
        _decision(
            decision_id="finding_status_assignment",
            phase="case_questions",
            question="Which status threshold does each case question meet?",
            available_inputs={"status_counts": status_counts},
            selected_action=(
                "Apply strict confirmed/inferred/needs_review/not_assessed/rejected rules."
            ),
            rationale=(
                "Unsupported or weak evidence must not be promoted to compromise or "
                "exfiltration claims."
            ),
            expected_outputs=["case_questions.json", "findings.json"],
            outcome="completed" if casebook is not None else "not_available",
            next_action="Record unsupported gaps.",
        ),
        _decision(
            decision_id="unsupported_question_gap_handling",
            phase="gap_analysis",
            question="Which questions require unsupported artifact classes?",
            available_inputs={"status_counts": status_counts},
            selected_action=(
                "Mark unsupported theft, transfer, exfiltration, and memory questions "
                "not_assessed."
            ),
            rationale=(
                "The final scope does not parse browser, cloud, USB, network, "
                "file-open, or memory artifacts."
            ),
            expected_outputs=["gap_analysis.json"],
            outcome="completed" if casebook is not None else "not_available",
            next_action="Generate case-question-aware report.",
        ),
        _decision(
            decision_id="report_generation",
            phase="report",
            question="How should results be presented for analyst review?",
            available_inputs={
                "output_ref_count": len(run.output_refs),
                "warning_count": len(warnings),
            },
            selected_action=(
                "Write concise case-question, finding, gap, provenance, and next-step "
                "sections."
            ),
            rationale=(
                "The report should be readable in a short demo and avoid unsupported "
                "overclaims."
            ),
            expected_outputs=["report.md"],
            outcome="completed",
            next_action="Review outputs and preserve generated files under ignored run paths.",
        ),
    ]
    return {
        "case_id": adapted.case_id,
        "created_at": created_at,
        "mode": "case_question_quality",
        "decisions": decisions,
        "casebook_present": casebook is not None,
        "warnings": list(warnings),
    }
