from __future__ import annotations

from typing import Any

THEFT_EXFILTRATION_SCOPE_BOUNDARY = (
    "The current artifact scope does not support a theft/exfiltration conclusion; "
    "additional artifacts such as browser history, cloud sync logs, network telemetry, "
    "removable-device artifacts, or memory analysis would be required."
)
THEFT_EXFILTRATION_STRICT_WORDING = (
    "SIFTGuard did not find sufficient support for a theft or exfiltration conclusion "
    "within the submitted artifact scope."
)
THEFT_EXFILTRATION_QUESTION_IDS = (
    "q_what_was_stolen",
    "q_where_transferred",
    "q_how_stolen",
)
REAL_GAP_QUESTION_IDS = (*THEFT_EXFILTRATION_QUESTION_IDS, "q_memory")
RECOMMENDED_NEXT_ARTIFACTS = (
    "browser history",
    "cloud sync logs",
    "network telemetry",
    "removable-device artifacts",
    "memory analysis",
)


def _questions_by_id(case_questions: dict[str, Any] | None) -> dict[str, dict[str, Any]]:
    if case_questions is None:
        return {}
    rows = case_questions.get("questions", [])
    if not isinstance(rows, list):
        return {}
    questions: dict[str, dict[str, Any]] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        question_id = row.get("question_id")
        if isinstance(question_id, str) and question_id:
            questions[question_id] = dict(row)
    return questions


def _not_assessed_ids(questions: dict[str, dict[str, Any]]) -> list[str]:
    return [
        question_id
        for question_id in REAL_GAP_QUESTION_IDS
        if questions.get(question_id, {}).get("status") == "not_assessed"
    ]


def build_self_correction_events(
    *,
    case_id: str,
    created_at: str,
    case_questions: dict[str, Any] | None,
) -> dict[str, Any]:
    questions = _questions_by_id(case_questions)
    not_assessed_ids = _not_assessed_ids(questions)
    theft_exfiltration_gap = all(
        question_id in not_assessed_ids for question_id in THEFT_EXFILTRATION_QUESTION_IDS
    )

    events: list[dict[str, Any]] = []
    if theft_exfiltration_gap:
        events.append(
            {
                "event_id": "real-gap-001",
                "phase": "claim_validation",
                "initial_investigative_pressure": (
                    "The ROCBA case asks what IP was stolen, how it was transferred, "
                    "and where it went."
                ),
                "problem_detected": (
                    "The submitted artifact scope does not contain sufficient support "
                    "for a theft/exfiltration conclusion."
                ),
                "correction": (
                    "The final posture was revised to not_assessed / insufficient "
                    "support within current artifact scope."
                ),
                "final_wording": THEFT_EXFILTRATION_STRICT_WORDING,
                "claim_boundary": THEFT_EXFILTRATION_SCOPE_BOUNDARY,
                "recommended_next_artifacts": list(RECOMMENDED_NEXT_ARTIFACTS),
                "source_question_ids": not_assessed_ids,
                "human_intervention": False,
                "model_output_used_as_evidence": False,
                "raw_evidence_sent_to_model": False,
            }
        )

    return {
        "case_id": case_id,
        "created_at": created_at,
        "mode": "real_gap_self_correction",
        "event_count": len(events),
        "events": events,
        "notes": [
            (
                "Events are generated by deterministic SIFTGuard validation from "
                "case-question statuses; OpenClaw may use them to revise narrative posture."
            )
        ],
    }
